# https://docs.pipewire.org/page_man_pipewire_conf_5.html
# PipeWire Dynamic Clocking & Resampling (48 kHz Studio & Video Standard)
context.properties = {
    default.clock.rate = 48000
    default.clock.allowed-rates = [ 48000 96000 192000 ]
    default.clock.quantum = 1024
    default.clock.min-quantum = 64
    default.clock.max-quantum = 2048
    resample.quality = 4
}
